export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0b1024] text-slate-100 flex items-center justify-center px-4 py-10">
      <div className="w-full max-w-[720px] rounded-3xl bg-white/5 px-6 py-7 sm:px-10 sm:py-10 shadow-[0_18px_60px_rgba(15,23,42,0.55)] backdrop-blur-md border border-white/10">
        <div className="mb-6 text-center">
          <p className="text-[13px] uppercase tracking-[0.18em] text-indigo-200/90">EMMA</p>
          <h1 className="mt-1 text-[22px] sm:text-[24px] font-semibold text-white">
            Privacy &amp; data use
          </h1>
          <p className="mt-2 text-[13px] text-slate-200/80">
            This page explains how your data is handled when you use EMMA.
          </p>
        </div>

        <div className="space-y-8 text-[14px] leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">1. Cosa fa EMMA (IT)</h2>
            <p className="text-slate-100/85">
              EMMA è uno spazio digitale pensato per aiutarti a mettere in parole ciò che provi. Le sue risposte
              vengono generate da un modello di intelligenza artificiale. Non è una professionista sanitaria e non
              sostituisce un percorso terapeutico.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">2. Quali dati vengono trattati (IT)</h2>
            <p className="text-slate-100/85">
              Quando scrivi nella chat, il testo che inserisci viene inviato ai server del fornitore di AI (OpenAI)
              per generare la risposta di EMMA. Non chiediamo di creare un account e non ti chiediamo dati anagrafici
              come nome, cognome o email.
            </p>
            <p className="text-slate-100/80">
              Ti invitiamo comunque a non inserire dati altamente sensibili (per esempio: indirizzi, codici fiscali,
              numeri di documenti o informazioni che permettono di identificare altre persone).
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">3. Come vengono usati i dati (IT)</h2>
            <p className="text-slate-100/85">
              Il contenuto delle conversazioni viene utilizzato al solo scopo di generare le risposte della chat e,
              in forma aggregata e anonima, per migliorare la qualità del servizio. I dati non vengono venduti a
              terze parti per finalità di marketing.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">4. Sicurezza (IT)</h2>
            <p className="text-slate-100/85">
              Ci impegniamo a proteggere i tuoi dati utilizzando connessioni sicure (HTTPS) e fornitori affidabili.
              Nessun sistema è perfetto, ma facciamo del nostro meglio per mantenere EMMA uno spazio sicuro e
              rispettoso.
            </p>
          </section>

          <section className="space-y-2 pt-2 border-t border-white/10">
            <h2 className="text-[15px] font-semibold text-white">1. What EMMA does (EN)</h2>
            <p className="text-slate-100/85">
              EMMA is a digital space designed to help you put your feelings into words. Her replies are generated by
              an AI model. She is not a healthcare professional and does not replace therapy or medical support.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">2. What data is processed (EN)</h2>
            <p className="text-slate-100/85">
              When you write in the chat, the text you enter is sent to the AI provider&apos;s servers (OpenAI) in order
              to generate EMMA&apos;s reply. We do not ask you to create an account and we do not request identity data
              such as your full name or email address.
            </p>
            <p className="text-slate-100/80">
              We still kindly ask you not to share highly sensitive details (for example: full addresses, tax IDs,
              document numbers or information that can clearly identify other people).
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">3. How your data is used (EN)</h2>
            <p className="text-slate-100/85">
              The content of conversations is used only to generate chat responses and, in aggregated and anonymised
              form, to understand how to improve the service. Data is not sold to third parties for marketing
              purposes.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-[15px] font-semibold text-white">4. Security (EN)</h2>
            <p className="text-slate-100/85">
              We do our best to protect your data by using secure connections (HTTPS) and trusted providers. No system
              is perfect, but we aim to keep EMMA a respectful and emotionally safe place for you.
            </p>
          </section>
        </div>

        <p className="mt-8 text-center text-[11px] text-slate-300/80">
          This page is a simplified overview and does not replace a full legal privacy policy. If you have questions
          or concerns about how your data is handled, please reach out through the contact details provided in the
          main website.
        </p>
      </div>
    </div>
  );
}
